############ Debugging arguments ############
seed: 42
# overwrite_output_dir: True
overwrite_output_dir: False
# max_train_samples: 1000
# max_eval_samples: 100
# max_predict_samples: 100

############ Data and model ############
dataset_name: BioDEX/BioDEX-ICSR
text_column: fulltext_processed
summary_column: target
#model_name_or_path: stanford-crfm/BioMedLM
model_name_or_path: ../../checkpoints/BioMedLM-BioDEX-ICSR-fulltext/checkpoint-16842/
tokenizer_name: stanford-crfm/BioMedLM
output_dir: ../../checkpoints/BioMedLM-BioDEX-ICSR-fulltext
max_source_length: 512
max_target_length: 510
do_train: False
do_eval: False
do_predict: True

############ Training parameters ############
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
per_device_predict_batch_size: 1 # Must always be equal to 1 to avoid padding issues with current code
gradient_accumulation_steps: 1
eval_accumulation_steps: 8
learning_rate: 0.0005
warmup_ratio: 0.1
weight_decay: 0.0
bf16: True
num_train_epochs: 10


############ Generation parameters ############
num_beams: 2
repetition_penalty: 1.2

############# Saving and logging ############
evaluation_strategy: epoch
logging_strategy: steps
save_strategy: epoch
# eval_steps: 20 # keep it low to see the curve in the beginning
logging_steps: 100
# save_steps: 1000
save_total_limit: 2
report_to: wandb
load_best_model_at_end: True
metric_for_best_model: loss
greater_is_better: False
